---
title: "Depression, HRV, and CAD Pilot Study"
subtitle: "MSCR Coursework"
author: 
- Anish Shah, MD^[Department of Medicine, School of Medicine, Emory University]
- Amit Shah, MD, MSCR^[Divison of Cardiology, Department of Medicine, Emory University]
- Alvaro Alonso, MD, PhD^[Department of Epidemiology, Rollins School of Public Health, Emory University]
date: "January 8, 2020"
fontsize: 10pt
output: 
  beamer_presentation:
    colortheme: "beaver"
    slide_level: 3
  latex_engine: xelatex
header-includes:
  - \usepackage{dcolumn}
  - \usepackage{float}
  - \usepackage{graphicx} 
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
always_allow_html: yes
---

```{r global_options, include=FALSE}

# Knitr options
knitr::opts_chunk$set(
  cache = TRUE,
  warning = FALSE,
  eval = TRUE,
  echo = FALSE,
  include = TRUE,
  message = FALSE,
  dpi = 600,
  dev = "png",
  options("scipen" = 999, "digits" = 3),
  tinytex.verbose = TRUE,
  tidy = FALSE
)

options(xtable.comment = FALSE)
```

```{r load up data, include = FALSE}
# Start time
alpha_time <- Sys.time()

# Libraries
source("../code/1_libraries.R")

# Read in the files
source("../code/2a_vivalnk.R")
source("../code/2b_hrv.R")
source("../code/2c_biobank.R")

# Source Tidying
source("../code/3_tidy.R")

# End of process
omega_time <- Sys.time()
cat("Time to load libraries, intake data, and tidy it...")
print(omega_time - alpha_time)
```


# Results

### Sample Overview

```{r, sample table 1}
df <- full_join(demo, psych, by = "patid") %>%
  full_join(., angio_scores, by = "patid") %>%
  full_join(., history, by = "patid")

# Relabel text-dependent variables
df$Admission_Reason <- df$adm_reason <- df_txt$adm_reason
df$Sex <- df$gend <- df_txt$gend
df$Race <- df$race <- df_txt$race
df$Setting <- df$setting <- df_txt$setting

# Merge in HRV
df %<>% full_join(., hrv_first_hour, by = "patid")

# Relabel important variables
df$Hypertension <- df$hyp %<>% factor()
df$Diabetes <- df$diab %<>% factor()
df$History_CAD <- df$cad %<>% factor()
df$CASS_70 <- df$cass70 %<>% factor()
df$Age <- df$age
df$BMI <- df$blbmi
df$Gensini <- df$gensini
df$PHQ <- df$phq
df$Depression <- df$sad

# Save this data set
big_df <- df[c("patid", "Sex", "Age", "Race", "BMI", "Setting", "Diabetes", "Hypertension", "PHQ", "Gensini", "CASS_70", "NN", "SDNN", "RMSSD", "PNN50", "ULF", "VLF", "LF", "HF", "TP", "LFHF", "AC", "DC", "SampEn", "ApEn", "DYX", "Depression")]

# Make table
compareGroups(~ Sex + Age + Race + BMI + Setting + Diabetes + Hypertension + PHQ + Gensini + CASS_70 + NN + SDNN + RMSSD + PNN50 + ULF + VLF + LF + HF + TP + LFHF + AC + DC + SampEn + ApEn + DYX, data = big_df) %>%
  createTable(show.p.overall = FALSE, hide.no = 0, hide = c(Sex = "Female")) %>%
  export2csv(file = "../figures/table-data-overview.csv")
```

### Depression and HRV

```{r depression}
# Data
df <- big_df
levels(df$Depression) <- c("Low Depression", "High Depression")

compareGroups(Depression ~ Sex + Age + Race + BMI + Setting + Diabetes + Hypertension + Gensini + CASS_70 + NN + SDNN + RMSSD + PNN50 + ULF + VLF + LF + HF + TP + LFHF + AC + DC + SampEn + ApEn + DYX, data = df) %>%
  createTable(show.p.overall = TRUE, show.ratio = TRUE, show.p.ratio = TRUE, digits = 2, hide.no = 0, hide = c(Sex = "Female")) %>% 
  export2csv(file = "../figures/table-depression-comparison.csv")
```

### CAD and HRV

```{r CAD overview}
# Data
df <- big_df
levels(df$Depression) <- c("Low Depression", "High Depression")
df$Obstructive_CAD <- ifelse(as.numeric(as.character(df$CASS_70)) >= 1, "Obstructive Dz", "No Obstructive Dz")

compareGroups(Obstructive_CAD ~ Sex + Age + Race + BMI + Setting + Diabetes + Hypertension + Depression + PHQ + NN + SDNN + RMSSD + PNN50 + ULF + VLF + LF + HF + TP + LFHF + AC + DC + SampEn + ApEn + DYX, data = df) %>%
  createTable(show.p.overall = TRUE, show.ratio = TRUE, show.p.ratio = TRUE, digits = 2, hide.no = 0, hide = c(Sex = "Female")) %>%
  export2csv(file = "../figures/table-cad-comparison.csv")
```
